/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnessapp.screens;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import fitnessapp.controllers.ActivityModalController;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author orion90
 */
public class ActivityModal extends javax.swing.JDialog {

    /**
     * Creates new form ActivityModal
     */
    private final String styleCard = "arc:20;";
    private final String flatStyle = FlatClientProperties.STYLE;

    public ActivityModal() {
        FlatRobotoFont.install();
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 15));
        FlatMacLightLaf.registerCustomDefaultsSource("fitnessapp.properties");
        FlatMacLightLaf.setup();
        this.setBackground(null);
        this.setUndecorated(true);
        initComponents();
       
        btnAdded.putClientProperty(flatStyle, "arc:20;background:@accentColor;foreground:#ffffff");
        btnAdded.setIcon(new FlatSVGIcon("fitnessapp/icons/plus.svg"));
        container.putClientProperty(flatStyle, "arc:20;background:#fff");
        btnClose.setIcon(new FlatSVGIcon("fitnessapp/icons/close.svg"));
        btnClose.putClientProperty(flatStyle, "buttonType:roundRect;borderColor:#fff");
    }

    public JButton getBtnAdded() {
        return btnAdded;
    }

    public void setBtnAdded(JButton btnAdded) {
        this.btnAdded = btnAdded;
    }

    public JButton getBtnClose() {
        return btnClose;
    }

    public void setBtnClose(JButton btnClose) {
        this.btnClose = btnClose;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    public JTextArea getTxtFDesc() {
        return txtFDesc;
    }

    public void setTxtFDesc(JTextArea txtFDesc) {
        this.txtFDesc = txtFDesc;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        center = new javax.swing.JPanel();
        labelContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        descContainer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFDesc = new javax.swing.JTextArea();
        subscContainer = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        btnAdded = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 600));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        container.setLayout(new java.awt.BorderLayout());

        header.setBackground(new java.awt.Color(220, 220, 220));
        header.setOpaque(false);
        header.setPreferredSize(new java.awt.Dimension(600, 60));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ajouter Activite");

        btnClose.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        container.add(header, java.awt.BorderLayout.PAGE_START);

        center.setBackground(new java.awt.Color(221, 221, 221));
        center.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 20));
        center.setOpaque(false);
        center.setLayout(new java.awt.GridLayout(3, 1, 10, 0));

        labelContainer.setBackground(new java.awt.Color(255, 255, 255));
        labelContainer.setMaximumSize(new java.awt.Dimension(400, 146));
        labelContainer.setMinimumSize(new java.awt.Dimension(400, 146));
        labelContainer.setName(""); // NOI18N
        labelContainer.setOpaque(false);
        labelContainer.setPreferredSize(new java.awt.Dimension(400, 146));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Label");

        javax.swing.GroupLayout labelContainerLayout = new javax.swing.GroupLayout(labelContainer);
        labelContainer.setLayout(labelContainerLayout);
        labelContainerLayout.setHorizontalGroup(
            labelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelContainerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(labelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        labelContainerLayout.setVerticalGroup(
            labelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelContainerLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        center.add(labelContainer);

        descContainer.setBackground(new java.awt.Color(255, 255, 255));
        descContainer.setMaximumSize(new java.awt.Dimension(400, 146));
        descContainer.setMinimumSize(new java.awt.Dimension(400, 146));
        descContainer.setOpaque(false);
        descContainer.setPreferredSize(new java.awt.Dimension(400, 146));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Descriptions");

        txtFDesc.setColumns(20);
        txtFDesc.setRows(5);
        jScrollPane1.setViewportView(txtFDesc);

        javax.swing.GroupLayout descContainerLayout = new javax.swing.GroupLayout(descContainer);
        descContainer.setLayout(descContainerLayout);
        descContainerLayout.setHorizontalGroup(
            descContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descContainerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(descContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        descContainerLayout.setVerticalGroup(
            descContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descContainerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        center.add(descContainer);

        subscContainer.setBackground(new java.awt.Color(255, 255, 255));
        subscContainer.setMaximumSize(new java.awt.Dimension(400, 146));
        subscContainer.setMinimumSize(new java.awt.Dimension(400, 146));
        subscContainer.setOpaque(false);
        subscContainer.setPreferredSize(new java.awt.Dimension(400, 146));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Abonnements");

        javax.swing.GroupLayout subscContainerLayout = new javax.swing.GroupLayout(subscContainer);
        subscContainer.setLayout(subscContainerLayout);
        subscContainerLayout.setHorizontalGroup(
            subscContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subscContainerLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addContainerGap(273, Short.MAX_VALUE))
            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        subscContainerLayout.setVerticalGroup(
            subscContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subscContainerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        center.add(subscContainer);

        container.add(center, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(221, 221, 221));
        footer.setOpaque(false);

        btnAdded.setText("Ajouter");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(btnAdded, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(btnAdded, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        container.add(footer, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdded;
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel center;
    private javax.swing.JPanel container;
    private javax.swing.JPanel descContainer;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel labelContainer;
    private javax.swing.JPanel subscContainer;
    private javax.swing.JTextArea txtFDesc;
    // End of variables declaration//GEN-END:variables
}
