/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnessapp.screens;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import fitnessapp.controllers.ActivityController;
import fitnessapp.controllers.CoachController;
import fitnessapp.controllers.MemberController;
import fitnessapp.controllers.RoomController;
import fitnessapp.models.AuthResponse;
import raven.toast.Notifications;

/**
 *
 * @author orion90
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private final String styleCard = "arc:20;";
    private final String flatStyle = FlatClientProperties.STYLE;
    private final ActivityController activityController;
    private final RoomController roomController;
    private final MemberController memberController;
    private final CoachController coachController;
    private final AuthResponse authResponse;
    public Dashboard(AuthResponse authResponse) {
        Notifications.getInstance().setJFrame(this);
        Notifications.getInstance().show(Notifications.Type.INFO, "Initialisation terminé.");
        this.authResponse=authResponse;
        initComponents();
        activityController = new ActivityController(this, btnAddActivity, inputSearchActivity,
                btnDeleteActivity, tableActivity,authResponse.authToken());
        roomController=new RoomController(this,btnDeleteRoom, btnAddRoom, tableRoom, inputSearchRoom);
        memberController=new MemberController(btnDeleteMember, btnAddMember, tableMember, inputSearchMember, this);
        coachController=new CoachController(inputSearchCoach, btnDeleteCoach, btnAddCoach, this);
        init();
    }

    private void init() {
        menu.setIconAt(0, new FlatSVGIcon("fitnessapp/icons/home.svg"));
        menu.setIconAt(1, new FlatSVGIcon("fitnessapp/icons/activity.svg"));
        menu.setIconAt(2, new FlatSVGIcon("fitnessapp/icons/planning.svg"));
        menu.setIconAt(3, new FlatSVGIcon("fitnessapp/icons/members.svg"));
        menu.setIconAt(4, new FlatSVGIcon("fitnessapp/icons/room.svg"));
        menu.setIconAt(5, new FlatSVGIcon("fitnessapp/icons/coach.svg"));
        menu.setIconAt(6, new FlatSVGIcon("fitnessapp/icons/user.svg"));
        menu.putClientProperty("FlatLaf.style", "font: semibold $h3.regular.font;");
        subscribeInfo.putClientProperty(flatStyle, styleCard + "background:#00ff7f30");
        subscribeInfoTotal.putClientProperty(flatStyle, styleCard + "background:#ff557f30");
        subscribeInfoMoney.putClientProperty(flatStyle, styleCard + "background:#aa55ff30");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        container = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        homeContainer = new javax.swing.JPanel();
        infoContainer = new javax.swing.JPanel();
        subscribeInfo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        subscribeInfoTotal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        subscribeInfoMoney = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tableInfoContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        activity = new javax.swing.JPanel();
        activityContainer = new javax.swing.JPanel();
        activityMain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableActivity = new javax.swing.JTable();
        activityHeader = new javax.swing.JPanel();
        activityHeaderLeft = new javax.swing.JPanel();
        btnDeleteActivity = new javax.swing.JButton();
        numberActivitiesSelected = new javax.swing.JLabel();
        activityHeaderCenter = new javax.swing.JPanel();
        inputSearchActivity = new javax.swing.JTextField();
        activityHeaderRight = new javax.swing.JPanel();
        btnAddActivity = new javax.swing.JButton();
        plannings = new javax.swing.JPanel();
        planningContainer = new javax.swing.JPanel();
        members = new javax.swing.JPanel();
        memberContainer = new javax.swing.JPanel();
        memberMain = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMember = new javax.swing.JTable();
        memberHeader = new javax.swing.JPanel();
        memberHeaderLeft = new javax.swing.JPanel();
        btnDeleteMember = new javax.swing.JButton();
        numberMemberSelected = new javax.swing.JLabel();
        memberHeaderCenter = new javax.swing.JPanel();
        inputSearchMember = new javax.swing.JTextField();
        memberHeaderRight = new javax.swing.JPanel();
        btnAddMember = new javax.swing.JButton();
        room = new javax.swing.JPanel();
        roomContainer = new javax.swing.JPanel();
        roomMain = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableRoom = new javax.swing.JTable();
        roomHeader = new javax.swing.JPanel();
        roomHeaderLeft = new javax.swing.JPanel();
        btnDeleteRoom = new javax.swing.JButton();
        numberRoomsSelected = new javax.swing.JLabel();
        roomHeaderCenter = new javax.swing.JPanel();
        inputSearchRoom = new javax.swing.JTextField();
        roomHeaderRight = new javax.swing.JPanel();
        btnAddRoom = new javax.swing.JButton();
        coach = new javax.swing.JPanel();
        coachContainer = new javax.swing.JPanel();
        coachMain = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableCoach = new javax.swing.JTable();
        coachHeader = new javax.swing.JPanel();
        coachHeaderLeft = new javax.swing.JPanel();
        btnDeleteCoach = new javax.swing.JButton();
        numberCoachSelected = new javax.swing.JLabel();
        coachHeaderCenter = new javax.swing.JPanel();
        inputSearchCoach = new javax.swing.JTextField();
        coachHeaderRight = new javax.swing.JPanel();
        btnAddCoach = new javax.swing.JButton();
        users = new javax.swing.JPanel();
        usersContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setName("dashboard"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 800));

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new java.awt.BorderLayout(5, 5));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setPreferredSize(new java.awt.Dimension(1200, 50));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MaiFitness");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(1077, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        container.add(header, java.awt.BorderLayout.PAGE_START);

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        menu.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 20, 5));
        home.setToolTipText("");
        home.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        home.setLayout(new java.awt.BorderLayout());

        homeContainer.setBackground(new java.awt.Color(255, 255, 255));
        homeContainer.setLayout(new java.awt.BorderLayout());

        infoContainer.setBackground(new java.awt.Color(255, 255, 255));
        infoContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 20, 20, 20));
        infoContainer.setPreferredSize(new java.awt.Dimension(1069, 200));
        infoContainer.setLayout(new java.awt.GridLayout(1, 1, 20, 0));

        subscribeInfo.setBackground(new java.awt.Color(51, 51, 255));
        subscribeInfo.setMaximumSize(new java.awt.Dimension(300, 150));

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel3.setText("Abonnes");

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabel5.setText("100 abonnes active");

        javax.swing.GroupLayout subscribeInfoLayout = new javax.swing.GroupLayout(subscribeInfo);
        subscribeInfo.setLayout(subscribeInfoLayout);
        subscribeInfoLayout.setHorizontalGroup(
            subscribeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subscribeInfoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(subscribeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subscribeInfoLayout.setVerticalGroup(
            subscribeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subscribeInfoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(61, 61, 61))
        );

        infoContainer.add(subscribeInfo);

        subscribeInfoTotal.setMaximumSize(new java.awt.Dimension(300, 150));

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel4.setText("Annees");

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabel2.setText("500 abonnes dans l'annees");

        javax.swing.GroupLayout subscribeInfoTotalLayout = new javax.swing.GroupLayout(subscribeInfoTotal);
        subscribeInfoTotal.setLayout(subscribeInfoTotalLayout);
        subscribeInfoTotalLayout.setHorizontalGroup(
            subscribeInfoTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subscribeInfoTotalLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(subscribeInfoTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subscribeInfoTotalLayout.setVerticalGroup(
            subscribeInfoTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subscribeInfoTotalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoContainer.add(subscribeInfoTotal);

        subscribeInfoMoney.setMaximumSize(new java.awt.Dimension(300, 150));

        jLabel6.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel6.setText("Montants annuels");

        jLabel7.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabel7.setText("1.000.000 FCFA");

        javax.swing.GroupLayout subscribeInfoMoneyLayout = new javax.swing.GroupLayout(subscribeInfoMoney);
        subscribeInfoMoney.setLayout(subscribeInfoMoneyLayout);
        subscribeInfoMoneyLayout.setHorizontalGroup(
            subscribeInfoMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subscribeInfoMoneyLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(subscribeInfoMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subscribeInfoMoneyLayout.setVerticalGroup(
            subscribeInfoMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subscribeInfoMoneyLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoContainer.add(subscribeInfoMoney);

        homeContainer.add(infoContainer, java.awt.BorderLayout.PAGE_START);

        tableInfoContainer.setBackground(new java.awt.Color(255, 255, 255));
        tableInfoContainer.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Date Debut", "Date Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tableInfoContainer.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        homeContainer.add(tableInfoContainer, java.awt.BorderLayout.CENTER);

        home.add(homeContainer, java.awt.BorderLayout.CENTER);

        menu.addTab("Accueil", null, home, "Accueil");

        activity.setBackground(new java.awt.Color(255, 255, 255));
        activity.setLayout(new java.awt.BorderLayout());

        activityContainer.setBackground(new java.awt.Color(255, 255, 255));
        activityContainer.setLayout(new java.awt.BorderLayout());

        activityMain.setLayout(new java.awt.BorderLayout());

        tableActivity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Label", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableActivity);

        activityMain.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        activityHeader.setPreferredSize(new java.awt.Dimension(1079, 60));
        activityHeader.setLayout(new java.awt.GridBagLayout());

        activityHeaderLeft.setMaximumSize(new java.awt.Dimension(200, 61));
        activityHeaderLeft.setPreferredSize(new java.awt.Dimension(200, 61));

        btnDeleteActivity.setBackground(new java.awt.Color(255, 0, 51));
        btnDeleteActivity.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        btnDeleteActivity.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteActivity.setText("Supprimer");
        btnDeleteActivity.setMinimumSize(new java.awt.Dimension(110, 50));
        btnDeleteActivity.setPreferredSize(new java.awt.Dimension(97, 50));
        btnDeleteActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActivityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout activityHeaderLeftLayout = new javax.swing.GroupLayout(activityHeaderLeft);
        activityHeaderLeft.setLayout(activityHeaderLeftLayout);
        activityHeaderLeftLayout.setHorizontalGroup(
            activityHeaderLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityHeaderLeftLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(numberActivitiesSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        activityHeaderLeftLayout.setVerticalGroup(
            activityHeaderLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityHeaderLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(activityHeaderLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberActivitiesSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        activityHeader.add(activityHeaderLeft, new java.awt.GridBagConstraints());

        activityHeaderCenter.setMinimumSize(new java.awt.Dimension(85, 50));
        activityHeaderCenter.setPreferredSize(new java.awt.Dimension(500, 38));
        activityHeaderCenter.setLayout(new java.awt.BorderLayout());

        inputSearchActivity.setPreferredSize(new java.awt.Dimension(95, 50));
        activityHeaderCenter.add(inputSearchActivity, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        activityHeader.add(activityHeaderCenter, gridBagConstraints);

        btnAddActivity.setBackground(new java.awt.Color(130, 185, 0));
        btnAddActivity.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        btnAddActivity.setForeground(new java.awt.Color(255, 255, 255));
        btnAddActivity.setText("Ajouter");
        btnAddActivity.setMinimumSize(new java.awt.Dimension(106, 50));
        btnAddActivity.setPreferredSize(new java.awt.Dimension(106, 50));

        javax.swing.GroupLayout activityHeaderRightLayout = new javax.swing.GroupLayout(activityHeaderRight);
        activityHeaderRight.setLayout(activityHeaderRightLayout);
        activityHeaderRightLayout.setHorizontalGroup(
            activityHeaderRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityHeaderRightLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAddActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        activityHeaderRightLayout.setVerticalGroup(
            activityHeaderRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, activityHeaderRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        activityHeader.add(activityHeaderRight, new java.awt.GridBagConstraints());

        activityMain.add(activityHeader, java.awt.BorderLayout.PAGE_START);

        activityContainer.add(activityMain, java.awt.BorderLayout.CENTER);

        activity.add(activityContainer, java.awt.BorderLayout.CENTER);

        menu.addTab("Activites", activity);

        plannings.setBackground(new java.awt.Color(255, 255, 255));
        plannings.setLayout(new java.awt.BorderLayout());

        planningContainer.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout planningContainerLayout = new javax.swing.GroupLayout(planningContainer);
        planningContainer.setLayout(planningContainerLayout);
        planningContainerLayout.setHorizontalGroup(
            planningContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
        );
        planningContainerLayout.setVerticalGroup(
            planningContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );

        plannings.add(planningContainer, java.awt.BorderLayout.CENTER);

        menu.addTab("Plannings", plannings);

        members.setBackground(new java.awt.Color(255, 255, 255));
        members.setLayout(new java.awt.BorderLayout());

        memberContainer.setBackground(new java.awt.Color(255, 255, 255));
        memberContainer.setLayout(new java.awt.BorderLayout());

        memberMain.setLayout(new java.awt.BorderLayout());

        tableMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Actions", "ID", "Label", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableMember);

        memberMain.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        memberHeader.setPreferredSize(new java.awt.Dimension(1079, 60));
        memberHeader.setLayout(new java.awt.GridBagLayout());

        memberHeaderLeft.setMaximumSize(new java.awt.Dimension(200, 61));
        memberHeaderLeft.setPreferredSize(new java.awt.Dimension(200, 61));

        btnDeleteMember.setBackground(new java.awt.Color(255, 0, 51));
        btnDeleteMember.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        btnDeleteMember.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteMember.setText("Supprimer");
        btnDeleteMember.setMinimumSize(new java.awt.Dimension(110, 50));
        btnDeleteMember.setPreferredSize(new java.awt.Dimension(97, 50));
        btnDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout memberHeaderLeftLayout = new javax.swing.GroupLayout(memberHeaderLeft);
        memberHeaderLeft.setLayout(memberHeaderLeftLayout);
        memberHeaderLeftLayout.setHorizontalGroup(
            memberHeaderLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberHeaderLeftLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(numberMemberSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteMember, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        memberHeaderLeftLayout.setVerticalGroup(
            memberHeaderLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberHeaderLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberHeaderLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberMemberSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        memberHeader.add(memberHeaderLeft, new java.awt.GridBagConstraints());

        memberHeaderCenter.setMinimumSize(new java.awt.Dimension(85, 50));
        memberHeaderCenter.setPreferredSize(new java.awt.Dimension(500, 38));
        memberHeaderCenter.setLayout(new java.awt.BorderLayout());

        inputSearchMember.setPreferredSize(new java.awt.Dimension(95, 50));
        memberHeaderCenter.add(inputSearchMember, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        memberHeader.add(memberHeaderCenter, gridBagConstraints);

        btnAddMember.setBackground(new java.awt.Color(130, 185, 0));
        btnAddMember.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        btnAddMember.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMember.setText("Ajouter");
        btnAddMember.setMinimumSize(new java.awt.Dimension(106, 50));
        btnAddMember.setPreferredSize(new java.awt.Dimension(106, 50));

        javax.swing.GroupLayout memberHeaderRightLayout = new javax.swing.GroupLayout(memberHeaderRight);
        memberHeaderRight.setLayout(memberHeaderRightLayout);
        memberHeaderRightLayout.setHorizontalGroup(
            memberHeaderRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberHeaderRightLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        memberHeaderRightLayout.setVerticalGroup(
            memberHeaderRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberHeaderRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        memberHeader.add(memberHeaderRight, new java.awt.GridBagConstraints());

        memberMain.add(memberHeader, java.awt.BorderLayout.PAGE_START);

        memberContainer.add(memberMain, java.awt.BorderLayout.CENTER);

        members.add(memberContainer, java.awt.BorderLayout.CENTER);

        menu.addTab("Membres", members);

        room.setBackground(new java.awt.Color(255, 255, 255));
        room.setLayout(new java.awt.BorderLayout());

        roomContainer.setBackground(new java.awt.Color(255, 255, 255));
        roomContainer.setLayout(new java.awt.BorderLayout());

        roomMain.setLayout(new java.awt.BorderLayout());

        tableRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Actions", "ID", "Label", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableRoom);

        roomMain.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        roomHeader.setPreferredSize(new java.awt.Dimension(1079, 60));
        roomHeader.setLayout(new java.awt.GridBagLayout());

        roomHeaderLeft.setMaximumSize(new java.awt.Dimension(200, 61));
        roomHeaderLeft.setPreferredSize(new java.awt.Dimension(200, 61));

        btnDeleteRoom.setBackground(new java.awt.Color(255, 0, 51));
        btnDeleteRoom.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        btnDeleteRoom.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteRoom.setText("Supprimer");
        btnDeleteRoom.setMinimumSize(new java.awt.Dimension(110, 50));
        btnDeleteRoom.setPreferredSize(new java.awt.Dimension(97, 50));
        btnDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomHeaderLeftLayout = new javax.swing.GroupLayout(roomHeaderLeft);
        roomHeaderLeft.setLayout(roomHeaderLeftLayout);
        roomHeaderLeftLayout.setHorizontalGroup(
            roomHeaderLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomHeaderLeftLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(numberRoomsSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        roomHeaderLeftLayout.setVerticalGroup(
            roomHeaderLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomHeaderLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roomHeaderLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberRoomsSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        roomHeader.add(roomHeaderLeft, new java.awt.GridBagConstraints());

        roomHeaderCenter.setMinimumSize(new java.awt.Dimension(85, 50));
        roomHeaderCenter.setPreferredSize(new java.awt.Dimension(500, 38));
        roomHeaderCenter.setLayout(new java.awt.BorderLayout());

        inputSearchRoom.setPreferredSize(new java.awt.Dimension(95, 50));
        roomHeaderCenter.add(inputSearchRoom, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        roomHeader.add(roomHeaderCenter, gridBagConstraints);

        btnAddRoom.setBackground(new java.awt.Color(130, 185, 0));
        btnAddRoom.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        btnAddRoom.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRoom.setText("Ajouter");
        btnAddRoom.setMinimumSize(new java.awt.Dimension(106, 50));
        btnAddRoom.setPreferredSize(new java.awt.Dimension(106, 50));

        javax.swing.GroupLayout roomHeaderRightLayout = new javax.swing.GroupLayout(roomHeaderRight);
        roomHeaderRight.setLayout(roomHeaderRightLayout);
        roomHeaderRightLayout.setHorizontalGroup(
            roomHeaderRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomHeaderRightLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roomHeaderRightLayout.setVerticalGroup(
            roomHeaderRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomHeaderRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        roomHeader.add(roomHeaderRight, new java.awt.GridBagConstraints());

        roomMain.add(roomHeader, java.awt.BorderLayout.PAGE_START);

        roomContainer.add(roomMain, java.awt.BorderLayout.CENTER);

        room.add(roomContainer, java.awt.BorderLayout.CENTER);

        menu.addTab("Salles", room);

        coach.setBackground(new java.awt.Color(255, 255, 255));
        coach.setLayout(new java.awt.BorderLayout());

        coachContainer.setBackground(new java.awt.Color(255, 255, 255));
        coachContainer.setLayout(new java.awt.BorderLayout());

        coachMain.setLayout(new java.awt.BorderLayout());

        tableCoach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Actions", "ID", "Label", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableCoach);

        coachMain.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        coachHeader.setPreferredSize(new java.awt.Dimension(1079, 60));
        coachHeader.setLayout(new java.awt.GridBagLayout());

        coachHeaderLeft.setMaximumSize(new java.awt.Dimension(200, 61));
        coachHeaderLeft.setPreferredSize(new java.awt.Dimension(200, 61));

        btnDeleteCoach.setBackground(new java.awt.Color(255, 0, 51));
        btnDeleteCoach.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        btnDeleteCoach.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCoach.setText("Supprimer");
        btnDeleteCoach.setMinimumSize(new java.awt.Dimension(110, 50));
        btnDeleteCoach.setPreferredSize(new java.awt.Dimension(97, 50));
        btnDeleteCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCoachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coachHeaderLeftLayout = new javax.swing.GroupLayout(coachHeaderLeft);
        coachHeaderLeft.setLayout(coachHeaderLeftLayout);
        coachHeaderLeftLayout.setHorizontalGroup(
            coachHeaderLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coachHeaderLeftLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(numberCoachSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        coachHeaderLeftLayout.setVerticalGroup(
            coachHeaderLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coachHeaderLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coachHeaderLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberCoachSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCoach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        coachHeader.add(coachHeaderLeft, new java.awt.GridBagConstraints());

        coachHeaderCenter.setMinimumSize(new java.awt.Dimension(85, 50));
        coachHeaderCenter.setPreferredSize(new java.awt.Dimension(500, 38));
        coachHeaderCenter.setLayout(new java.awt.BorderLayout());

        inputSearchCoach.setPreferredSize(new java.awt.Dimension(95, 50));
        coachHeaderCenter.add(inputSearchCoach, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        coachHeader.add(coachHeaderCenter, gridBagConstraints);

        btnAddCoach.setBackground(new java.awt.Color(130, 185, 0));
        btnAddCoach.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        btnAddCoach.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCoach.setText("Ajouter");
        btnAddCoach.setMinimumSize(new java.awt.Dimension(106, 50));
        btnAddCoach.setPreferredSize(new java.awt.Dimension(106, 50));

        javax.swing.GroupLayout coachHeaderRightLayout = new javax.swing.GroupLayout(coachHeaderRight);
        coachHeaderRight.setLayout(coachHeaderRightLayout);
        coachHeaderRightLayout.setHorizontalGroup(
            coachHeaderRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coachHeaderRightLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAddCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        coachHeaderRightLayout.setVerticalGroup(
            coachHeaderRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coachHeaderRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        coachHeader.add(coachHeaderRight, new java.awt.GridBagConstraints());

        coachMain.add(coachHeader, java.awt.BorderLayout.PAGE_START);

        coachContainer.add(coachMain, java.awt.BorderLayout.CENTER);

        coach.add(coachContainer, java.awt.BorderLayout.CENTER);

        menu.addTab("Entraineurs", coach);

        users.setBackground(new java.awt.Color(255, 255, 255));
        users.setLayout(new java.awt.BorderLayout());

        usersContainer.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout usersContainerLayout = new javax.swing.GroupLayout(usersContainer);
        usersContainer.setLayout(usersContainerLayout);
        usersContainerLayout.setHorizontalGroup(
            usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
        );
        usersContainerLayout.setVerticalGroup(
            usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );

        users.add(usersContainer, java.awt.BorderLayout.CENTER);

        menu.addTab("Utilisateurs", users);

        container.add(menu, java.awt.BorderLayout.CENTER);

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActivityActionPerformed

    private void btnDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteRoomActionPerformed

    private void btnDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMemberActionPerformed

    private void btnDeleteCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCoachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCoachActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activity;
    private javax.swing.JPanel activityContainer;
    private javax.swing.JPanel activityHeader;
    private javax.swing.JPanel activityHeaderCenter;
    private javax.swing.JPanel activityHeaderLeft;
    private javax.swing.JPanel activityHeaderRight;
    private javax.swing.JPanel activityMain;
    private javax.swing.JButton btnAddActivity;
    private javax.swing.JButton btnAddCoach;
    private javax.swing.JButton btnAddMember;
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnDeleteActivity;
    private javax.swing.JButton btnDeleteCoach;
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnDeleteRoom;
    private javax.swing.JPanel coach;
    private javax.swing.JPanel coachContainer;
    private javax.swing.JPanel coachHeader;
    private javax.swing.JPanel coachHeaderCenter;
    private javax.swing.JPanel coachHeaderLeft;
    private javax.swing.JPanel coachHeaderRight;
    private javax.swing.JPanel coachMain;
    private javax.swing.JPanel container;
    private javax.swing.JPanel header;
    private javax.swing.JPanel home;
    private javax.swing.JPanel homeContainer;
    private javax.swing.JPanel infoContainer;
    private javax.swing.JTextField inputSearchActivity;
    private javax.swing.JTextField inputSearchCoach;
    private javax.swing.JTextField inputSearchMember;
    private javax.swing.JTextField inputSearchRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel memberContainer;
    private javax.swing.JPanel memberHeader;
    private javax.swing.JPanel memberHeaderCenter;
    private javax.swing.JPanel memberHeaderLeft;
    private javax.swing.JPanel memberHeaderRight;
    private javax.swing.JPanel memberMain;
    private javax.swing.JPanel members;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JLabel numberActivitiesSelected;
    private javax.swing.JLabel numberCoachSelected;
    private javax.swing.JLabel numberMemberSelected;
    private javax.swing.JLabel numberRoomsSelected;
    private javax.swing.JPanel planningContainer;
    private javax.swing.JPanel plannings;
    private javax.swing.JPanel room;
    private javax.swing.JPanel roomContainer;
    private javax.swing.JPanel roomHeader;
    private javax.swing.JPanel roomHeaderCenter;
    private javax.swing.JPanel roomHeaderLeft;
    private javax.swing.JPanel roomHeaderRight;
    private javax.swing.JPanel roomMain;
    private javax.swing.JPanel subscribeInfo;
    private javax.swing.JPanel subscribeInfoMoney;
    private javax.swing.JPanel subscribeInfoTotal;
    private javax.swing.JTable tableActivity;
    private javax.swing.JTable tableCoach;
    private javax.swing.JPanel tableInfoContainer;
    private javax.swing.JTable tableMember;
    private javax.swing.JTable tableRoom;
    private javax.swing.JPanel users;
    private javax.swing.JPanel usersContainer;
    // End of variables declaration//GEN-END:variables
}
